---

github_workflows:
  ansible_vsphere_vm_provision:
    main_admin_user:
      - duongvanthanh1992

  ansible_vsphere_vm_scan:
    main_admin_user:
      - duongvanthanh1992

  ansible_vsphere_vm_snapshot:
    main_admin_user:
      - duongvanthanh1992
