---

- hosts: "{{ input_target_group }}"
  gather_facts: true
  tasks:
    - name: Include role to validate decommission VM
      include_role:
        name: vm_decom_validate
      when: decom_run_phase == "validate"

    - name: Include role to execute decommission VM
      include_role:
        name: vm_decom_execute
      when: decom_run_phase == "execute"
