---
roles:
  - name: robertdebock.rsyslog
    version: 2.4.2
  - name: geerlingguy.mysql
    version: 3.3.2
  - name: evrardjp.keepalived
    version: 6.0.0
  - name: monolithprojects.github_actions_runner
    version: 1.15.2

collections:
  - name: amazon.aws
  - name: ansible.posix
  - name: ansible.windows
  - name: ansible.netcommon
  - name: ansible.utils
  - name: community.general
  - name: community.hashi_vault
  - name: community.docker
  - name: community.zabbix
  - name: community.grafana
  - name: community.mysql
  - name: community.vmware
