name: Ansible vSphere VM Scanning Pipeline
run-name: >
  [${{ github.ref_name }}] ${{ inputs.build_site }} | Group/VM: ${{ inputs.target_group }} |
  State: ${{ inputs.target_state }} | CR: ${{ inputs.change_request_number }}

on:
  workflow_dispatch:
    inputs:

      change_request_number: 
        description: "ServiceNow Change Request ID (e.g., CHG0000001). Mandatory for tracking."
        required: true
        default: "CHG0000001"

      build_site:
        type: choice
        description: "Deployment environment/site (e.g., SAT, PRD)."
        required: true
        default: "sat-sg1n"
        options:
          - "sat-sg1n"
          - "prd-sg1n"

      target_group:
        description: "Target host group(s) or VM(s) from Ansible inventory. 
          Use commas for multiple groups (e.g., vm-db,vm-non-db) or multiple VMs."
        required: true
        default: "vm-db,vm-non-db"

permissions:
  contents: read
  packages: read

concurrency:
  group: ansible-scan-${{ github.ref }}-${{ inputs.build_site }}-${{ inputs.target_group }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash -euo pipefail {0}

env:
  ANSIBLE_COLLECTIONS_PATH: /root/.ansible/collections:/usr/share/ansible/collections

jobs:

  pre:
    runs-on: [self-hosted]
    container:
      image: ubuntu:20.04
    steps:
      - uses: actions/checkout@v5

      - name: Load env from default location
        run: >-
          grep -v -e '^\s*#' -e '^\s*$' "build-env/${{ inputs.build_site }}.env"
          >> $GITHUB_ENV

    outputs:
      ansible_runner: ${{ env.ANSIBLE_RUNNER }}
      ansible_image: ${{ env.ANSIBLE_IMAGE }}

  access-check:
    needs: [pre]
    runs-on: [self-hosted, "${{ needs.pre.outputs.ansible_runner }}"]
    container:
          image: "${{ needs.pre.outputs.ansible_image }}"
    steps:
      - uses: actions/checkout@v5

      - name: Block production on non-main branches
        if: inputs.build_site == 'prd-sg1n' && github.ref_name != 'main'
        run: |
          TARGET_ENV="${{ inputs.build_site }}"
          CURRENT_BRANCH="${{ github.ref_name }}"

          echo "==========================================="
          echo "Production deployment blocked"
          echo "-------------------------------------------"
          echo " Branch : $CURRENT_BRANCH"
          echo " Env    : $TARGET_ENV"
          echo " Reason : Only 'main' branch can deploy prod"
          echo "==========================================="
          exit 1

      - name: Check workflow access (main branch only)
        run: |
          CURRENT_USER="${{ github.actor }}"
          CURRENT_BRANCH="${{ github.ref_name }}"
          CONFIG_FILE=".github/workflows_control/user_access.yml"
          WORKFLOW_NAME="ansible_vsphere_vm_scan"
          AUTHORIZED_USERS="$(yq eval ".github_workflows.\"${WORKFLOW_NAME}\".main_admin_user[]" "$CONFIG_FILE" 2>/dev/null || true)"

          if [ "$CURRENT_BRANCH" != "main" ]; then
            echo "Non-main branch: auth bypassed (prod already blocked)"
            exit 0
          fi

          if [ ! -f "$CONFIG_FILE" ]; then
            echo "Config file not found: $CONFIG_FILE"
            exit 1
          fi

          if [ -z "$AUTHORIZED_USERS" ]; then
            echo "No main_admin_user configured for workflow: $WORKFLOW_NAME"
            exit 1
          fi

          if ! printf '%s\n' "$AUTHORIZED_USERS" | grep -qx -- "$CURRENT_USER"; then
            echo "User '$CURRENT_USER' not authorized on main"
            echo "Allowed: $(echo "$AUTHORIZED_USERS" | tr '\n' ' ')"
            exit 1
          fi

          echo "'$CURRENT_USER' authorized for this workflow on main"

  validate:
    needs: [pre, access-check]
    runs-on: [self-hosted, "${{ needs.pre.outputs.ansible_runner }}"]
    environment: "${{ inputs.build_site }}-validation"
    container:
          image: "${{ needs.pre.outputs.ansible_image }}"
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /opt/ssh_key/private_ssh_key:/secrets/private_ssh_key:ro
          credentials:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Load env from ${{ inputs.build_site }} location
        run: >-
          grep -v -e '^\s*#' -e '^\s*$' "build-env/${{ inputs.build_site }}.env"
          >> $GITHUB_ENV

      - name: Stage SSH key
        working-directory: ansible/
        run: |
          cp /secrets/private_ssh_key ./private_ssh_key
          chmod 600 ./private_ssh_key

      # DEBUG
      - name: Print env
        run: |
          printenv

      # DEBUG
      - name: Print ansible version
        working-directory: ansible/
        run: |
          ansible-playbook --version
          ansible-galaxy collection list || true

      - name: Ansible check
        env:
          ANSIBLE_HASHI_VAULT_ADDR: ${{ secrets.ANSIBLE_HASHI_VAULT_ADDR }}
          ANSIBLE_HASHI_VAULT_TOKEN: ${{ secrets.ANSIBLE_HASHI_VAULT_TOKEN }}
          ANSIBLE_HASHI_VAULT_PATH_BASE: ${{ secrets.ANSIBLE_HASHI_VAULT_PATH_BASE }}
        id: ansible_check
        working-directory: ansible/
        run: >-
          ansible-playbook
          -i inventories/${{ inputs.build_site }}/hosts
          -e "input_build_site=${{ inputs.build_site }}"
          -e "input_target_group=${{ inputs.target_group }}"
          -e "change_request_number=${{ inputs.change_request_number }}"
          -e "workflow_initiator=${{ github.actor }}"
          prepare_environment.yml --tags ansible_check

  apply:
    needs: [pre, validate]
    runs-on: [self-hosted, "${{ needs.pre.outputs.ansible_runner }}"]
    environment: "${{ inputs.build_site }}-approved"
    container:
          image: "${{ needs.pre.outputs.ansible_image }}"
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /opt/ssh_key/private_ssh_key:/secrets/private_ssh_key:ro
          credentials:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Load env from ${{ inputs.build_site }} location
        run: >-
          grep -v -e '^\s*#' -e '^\s*$' "build-env/${{ inputs.build_site }}.env"
          >> $GITHUB_ENV

      - name: Stage SSH key
        working-directory: ansible/
        run: |
          cp /secrets/private_ssh_key ./private_ssh_key
          chmod 600 ./private_ssh_key

      - name: Ansible run
        env:
          ANSIBLE_HASHI_VAULT_ADDR: ${{ secrets.ANSIBLE_HASHI_VAULT_ADDR }}
          ANSIBLE_HASHI_VAULT_TOKEN: ${{ secrets.ANSIBLE_HASHI_VAULT_TOKEN }}
          ANSIBLE_HASHI_VAULT_PATH_BASE: ${{ secrets.ANSIBLE_HASHI_VAULT_PATH_BASE }}
        id: ansible_run
        working-directory: ansible/
        run: >-
          ansible-playbook
          -i inventories/${{ inputs.build_site }}/hosts
          -e "input_build_site=${{ inputs.build_site }}"
          -e "input_target_group=${{ inputs.target_group }}"
          -e "change_request_number=${{ inputs.change_request_number }}"
          -e "workflow_initiator=${{ github.actor }}"
          prepare_environment.yml
