---

vsphere_validate: false
enable_root_login: true
vsphere_resource_pool: "{{ lookup('env', 'VSPHERE_RESOURCE_POOL') }}"
vsphere_folder: "{{ lookup('env', 'VSPHERE_FOLDER') }}"
vsphere_datastore: "{{ lookup('env', 'VSPHERE_DATASTORE') }}"



hv: "community.hashi_vault.hashi_vault"
hv_query_base: >-
  secret=kv/vcenter/